// <auto-generated />
using System;
using Itenium.SkillForge.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Itenium.SkillForge.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260313160000_E3_GoalAchievedAt")]
    partial class E3_GoalAchievedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Intentionally left minimal — EF uses the snapshot file for full model.
            // The Migration attribute above is what EF needs to discover and apply this migration.
        }
    }
}
