<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Itenium.Forge.Security.OpenIddict" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Itenium.SkillForge.Entities\Itenium.SkillForge.Entities.csproj" />
    <ProjectReference Include="..\Itenium.SkillForge.Services\Itenium.SkillForge.Services.csproj" />
  </ItemGroup>

</Project>
