/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSkillsRouteImport } from './routes/_authenticated/skills'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRoadmapRouteImport } from './routes/_authenticated/roadmap'
import { Route as AuthenticatedResourcesRouteImport } from './routes/_authenticated/resources'
import { Route as AuthenticatedGoalsRouteImport } from './routes/_authenticated/goals'
import { Route as AuthenticatedCoursesRouteImport } from './routes/_authenticated/courses'
import { Route as AuthenticatedContactRouteImport } from './routes/_authenticated/contact'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/_admin/route'
import { Route as AuthenticatedSkillsIndexRouteImport } from './routes/_authenticated/skills.index'
import { Route as AuthenticatedSkillsSkillIdRouteImport } from './routes/_authenticated/skills.$skillId'
import { Route as AuthenticatedReportsTestRouteImport } from './routes/_authenticated/reports/test'
import { Route as AuthenticatedCoachDashboardRouteImport } from './routes/_authenticated/coach.dashboard'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/_admin/users'
import { Route as AuthenticatedCoachSessionsSessionIdRouteImport } from './routes/_authenticated/coach.sessions.$sessionId'
import { Route as AuthenticatedCoachConsultantsUserIdRouteImport } from './routes/_authenticated/coach.consultants.$userId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSkillsRoute = AuthenticatedSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoadmapRoute = AuthenticatedRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResourcesRoute = AuthenticatedResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGoalsRoute = AuthenticatedGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoursesRoute = AuthenticatedCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactRoute = AuthenticatedContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSkillsIndexRoute =
  AuthenticatedSkillsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSkillsRoute,
  } as any)
const AuthenticatedSkillsSkillIdRoute =
  AuthenticatedSkillsSkillIdRouteImport.update({
    id: '/$skillId',
    path: '/$skillId',
    getParentRoute: () => AuthenticatedSkillsRoute,
  } as any)
const AuthenticatedReportsTestRoute =
  AuthenticatedReportsTestRouteImport.update({
    id: '/reports/test',
    path: '/reports/test',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoachDashboardRoute =
  AuthenticatedCoachDashboardRouteImport.update({
    id: '/coach/dashboard',
    path: '/coach/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedCoachSessionsSessionIdRoute =
  AuthenticatedCoachSessionsSessionIdRouteImport.update({
    id: '/coach/sessions/$sessionId',
    path: '/coach/sessions/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoachConsultantsUserIdRoute =
  AuthenticatedCoachConsultantsUserIdRouteImport.update({
    id: '/coach/consultants/$userId',
    path: '/coach/consultants/$userId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/sign-in': typeof authSignInRoute
  '/contact': typeof AuthenticatedContactRoute
  '/courses': typeof AuthenticatedCoursesRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/resources': typeof AuthenticatedResourcesRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/skills': typeof AuthenticatedSkillsRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/users': typeof AuthenticatedAdminUsersRoute
  '/coach/dashboard': typeof AuthenticatedCoachDashboardRoute
  '/reports/test': typeof AuthenticatedReportsTestRoute
  '/skills/$skillId': typeof AuthenticatedSkillsSkillIdRoute
  '/skills/': typeof AuthenticatedSkillsIndexRoute
  '/coach/consultants/$userId': typeof AuthenticatedCoachConsultantsUserIdRoute
  '/coach/sessions/$sessionId': typeof AuthenticatedCoachSessionsSessionIdRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof authSignInRoute
  '/contact': typeof AuthenticatedContactRoute
  '/courses': typeof AuthenticatedCoursesRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/resources': typeof AuthenticatedResourcesRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/users': typeof AuthenticatedAdminUsersRoute
  '/coach/dashboard': typeof AuthenticatedCoachDashboardRoute
  '/reports/test': typeof AuthenticatedReportsTestRoute
  '/skills/$skillId': typeof AuthenticatedSkillsSkillIdRoute
  '/skills': typeof AuthenticatedSkillsIndexRoute
  '/coach/consultants/$userId': typeof AuthenticatedCoachConsultantsUserIdRoute
  '/coach/sessions/$sessionId': typeof AuthenticatedCoachSessionsSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/_authenticated/contact': typeof AuthenticatedContactRoute
  '/_authenticated/courses': typeof AuthenticatedCoursesRoute
  '/_authenticated/goals': typeof AuthenticatedGoalsRoute
  '/_authenticated/resources': typeof AuthenticatedResourcesRoute
  '/_authenticated/roadmap': typeof AuthenticatedRoadmapRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/skills': typeof AuthenticatedSkillsRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/_admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/coach/dashboard': typeof AuthenticatedCoachDashboardRoute
  '/_authenticated/reports/test': typeof AuthenticatedReportsTestRoute
  '/_authenticated/skills/$skillId': typeof AuthenticatedSkillsSkillIdRoute
  '/_authenticated/skills/': typeof AuthenticatedSkillsIndexRoute
  '/_authenticated/coach/consultants/$userId': typeof AuthenticatedCoachConsultantsUserIdRoute
  '/_authenticated/coach/sessions/$sessionId': typeof AuthenticatedCoachSessionsSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/sign-in'
    | '/contact'
    | '/courses'
    | '/goals'
    | '/resources'
    | '/roadmap'
    | '/settings'
    | '/skills'
    | '/'
    | '/users'
    | '/coach/dashboard'
    | '/reports/test'
    | '/skills/$skillId'
    | '/skills/'
    | '/coach/consultants/$userId'
    | '/coach/sessions/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/contact'
    | '/courses'
    | '/goals'
    | '/resources'
    | '/roadmap'
    | '/settings'
    | '/'
    | '/users'
    | '/coach/dashboard'
    | '/reports/test'
    | '/skills/$skillId'
    | '/skills'
    | '/coach/consultants/$userId'
    | '/coach/sessions/$sessionId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/_admin'
    | '/(auth)/sign-in'
    | '/_authenticated/contact'
    | '/_authenticated/courses'
    | '/_authenticated/goals'
    | '/_authenticated/resources'
    | '/_authenticated/roadmap'
    | '/_authenticated/settings'
    | '/_authenticated/skills'
    | '/_authenticated/'
    | '/_authenticated/_admin/users'
    | '/_authenticated/coach/dashboard'
    | '/_authenticated/reports/test'
    | '/_authenticated/skills/$skillId'
    | '/_authenticated/skills/'
    | '/_authenticated/coach/consultants/$userId'
    | '/_authenticated/coach/sessions/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/skills': {
      id: '/_authenticated/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AuthenticatedSkillsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roadmap': {
      id: '/_authenticated/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AuthenticatedRoadmapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resources': {
      id: '/_authenticated/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AuthenticatedResourcesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/goals': {
      id: '/_authenticated/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthenticatedGoalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses': {
      id: '/_authenticated/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AuthenticatedCoursesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contact': {
      id: '/_authenticated/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof AuthenticatedContactRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/skills/': {
      id: '/_authenticated/skills/'
      path: '/'
      fullPath: '/skills/'
      preLoaderRoute: typeof AuthenticatedSkillsIndexRouteImport
      parentRoute: typeof AuthenticatedSkillsRoute
    }
    '/_authenticated/skills/$skillId': {
      id: '/_authenticated/skills/$skillId'
      path: '/$skillId'
      fullPath: '/skills/$skillId'
      preLoaderRoute: typeof AuthenticatedSkillsSkillIdRouteImport
      parentRoute: typeof AuthenticatedSkillsRoute
    }
    '/_authenticated/reports/test': {
      id: '/_authenticated/reports/test'
      path: '/reports/test'
      fullPath: '/reports/test'
      preLoaderRoute: typeof AuthenticatedReportsTestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coach/dashboard': {
      id: '/_authenticated/coach/dashboard'
      path: '/coach/dashboard'
      fullPath: '/coach/dashboard'
      preLoaderRoute: typeof AuthenticatedCoachDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin/users': {
      id: '/_authenticated/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/coach/sessions/$sessionId': {
      id: '/_authenticated/coach/sessions/$sessionId'
      path: '/coach/sessions/$sessionId'
      fullPath: '/coach/sessions/$sessionId'
      preLoaderRoute: typeof AuthenticatedCoachSessionsSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coach/consultants/$userId': {
      id: '/_authenticated/coach/consultants/$userId'
      path: '/coach/consultants/$userId'
      fullPath: '/coach/consultants/$userId'
      preLoaderRoute: typeof AuthenticatedCoachConsultantsUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedSkillsRouteChildren {
  AuthenticatedSkillsSkillIdRoute: typeof AuthenticatedSkillsSkillIdRoute
  AuthenticatedSkillsIndexRoute: typeof AuthenticatedSkillsIndexRoute
}

const AuthenticatedSkillsRouteChildren: AuthenticatedSkillsRouteChildren = {
  AuthenticatedSkillsSkillIdRoute: AuthenticatedSkillsSkillIdRoute,
  AuthenticatedSkillsIndexRoute: AuthenticatedSkillsIndexRoute,
}

const AuthenticatedSkillsRouteWithChildren =
  AuthenticatedSkillsRoute._addFileChildren(AuthenticatedSkillsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedContactRoute: typeof AuthenticatedContactRoute
  AuthenticatedCoursesRoute: typeof AuthenticatedCoursesRoute
  AuthenticatedGoalsRoute: typeof AuthenticatedGoalsRoute
  AuthenticatedResourcesRoute: typeof AuthenticatedResourcesRoute
  AuthenticatedRoadmapRoute: typeof AuthenticatedRoadmapRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSkillsRoute: typeof AuthenticatedSkillsRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCoachDashboardRoute: typeof AuthenticatedCoachDashboardRoute
  AuthenticatedReportsTestRoute: typeof AuthenticatedReportsTestRoute
  AuthenticatedCoachConsultantsUserIdRoute: typeof AuthenticatedCoachConsultantsUserIdRoute
  AuthenticatedCoachSessionsSessionIdRoute: typeof AuthenticatedCoachSessionsSessionIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedContactRoute: AuthenticatedContactRoute,
  AuthenticatedCoursesRoute: AuthenticatedCoursesRoute,
  AuthenticatedGoalsRoute: AuthenticatedGoalsRoute,
  AuthenticatedResourcesRoute: AuthenticatedResourcesRoute,
  AuthenticatedRoadmapRoute: AuthenticatedRoadmapRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSkillsRoute: AuthenticatedSkillsRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCoachDashboardRoute: AuthenticatedCoachDashboardRoute,
  AuthenticatedReportsTestRoute: AuthenticatedReportsTestRoute,
  AuthenticatedCoachConsultantsUserIdRoute:
    AuthenticatedCoachConsultantsUserIdRoute,
  AuthenticatedCoachSessionsSessionIdRoute:
    AuthenticatedCoachSessionsSessionIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
