<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Itenium.Forge.Security" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Itenium.SkillForge.Entities\Itenium.SkillForge.Entities.csproj" />
  </ItemGroup>

</Project>
